export const EVENTS = {
  CURRENT_SCENE_READY: 'CURRENT_SCENE_READY',
  PLAYER_GAINED_LEVEL: 'PLAYER_GAINED_LEVEL',
  PLAYER_GAINED_EXPERIENCE: 'PLAYER_GAINED_EXPERIENCE',
  ENEMY_KILLED: 'ENEMY_KILLED',
  PLAYER_STATE_CHANGED: 'PLAYER_STATE_CHANGED',
  RESIZE: 'RESIZE',
  GAME_STATE_CHANGED: 'GAME_STATE_CHANGED',
  NEXT_LEVEL: 'NEXT_LEVEL',
  ENEMY_DIED: 'ENEMY_DIED',
};
